export const dataMatch = [
  {
    groupStage: "Solo_round_1",
    date: "25/11",
    home: "sonnx",
    away: "kynh",
    score: [3, 0],
    id: 1,
  },

  {
    groupStage: "Solo_round_1",
    date: "25/11",
    home: "huannd",
    away: "duchm",
    score: [3, 1],
    id: 2,
  },
  {
    groupStage: "Solo_round_1",
    date: "25/11",
    home: "cuongld",
    away: "tuannd",
    score: [2, 0],
    id: 3,
  },
  {
    groupStage: "Solo_round_1",
    date: "25/11",
    home: "taivd",
    away: "lamndh",
    score: [1, 0],
    id: 4,
  },
  {
    groupStage: "Solo_round_1",
    date: "25/11",
    home: "thanhnx",
    away: "truongdv",
    score: [0, 1],
    id: 5,
  },
  {
    groupStage: "Solo_round_1",
    date: "25/11",
    home: "kynh",
    away: "duchm",
    score: [5, 1],
    id: 6,
  },
  {
    groupStage: "Solo_round_1",
    date: "25/11",
    home: "tuannd",
    away: "truongdv",
    score: [0, 0],
    id: 7,
  },
  {
    groupStage: "Solo_round_1",
    date: "28/02",
    home: "taivd",
    away: "huypq",
    score: [0, 0],
    id: 8,
  },
  {
    groupStage: "Solo_round_1",
    date: "28/02",
    home: "thanhnx",
    away: "sonnx",
    score: [0, 2],
    id: 9,
  },
  {
    groupStage: "Solo_round_1",
    date: "28/02",
    home: "huannd",
    away: "huypq",
    score: [4, 0],
    id: 10,
  },
  {
    groupStage: "Solo_round_1",
    date: "02/03",
    home: "taivd",
    away: "tuannd",
    score: [0, 1],
    id: 11,
  },
  {
    groupStage: "Solo_round_1",
    date: "02/03",
    home: "huannd",
    away: "kynh",
    score: [0, 0],
    id: 12,
  },

  {
    groupStage: "Solo_round_1",
    date: "03/03",
    home: "cuongld",
    away: "lamndh",
    score: [4, 0],
    id: 13,
  },

  {
    groupStage: "Solo_round_1",
    date: "03/03",
    home: "cuongld",
    away: "taivd",
    score: [1, 0],
    id: 14,
  },

  {
    groupStage: "Solo_round_1",
    date: "03/03",
    home: "tuannd",
    away: "sonnx",
    score: [3, 0],
    id: 15,
  },
];
