//Vòng đấu bảng: 48 trận
//Vòng 16 đội: 8 trận
//Vòng tứ kết: 4 trận
//Vòng bán kết: 2 trận
//Trận tranh hạng ba
//Trận chung kết 

export const MatchApi = {
  "20/11": [
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Al Bayt Stadium",
      "linkStadium": "https://www.google.com/search?q=Al Bayt Stadium",
      "date": "20/11",
      "video": "https://www.youtube.com/watch?v=YtvePnAxYCk&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "5:22",
      "table": "Bảng A",
      "team1": "Qatar",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Qatar",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/h0FNA5YxLzWChHS5K0o4gw_96x96.png",
      "team2": "Ecuador",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Ecuador",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/AKqvkBpIyr-iLOK7Ig7-yQ_96x96.png",
      "score": [0, 2],
      "scorerName1": [''],
      "scorerName2": ["Enner Valencia 16', 31'"],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/RcwQgdJiYpRx1gL9_768x432.jpg",
      "id": "1"
    }
  ],
  "21/11": [
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Sân vận động Quốc tế Khalifa",
      "linkStadium": "https://www.google.com/search?q=Sân vận động Quốc tế Khalifa",
      "date": "21/11",
      "video": "https://www.youtube.com/watch?v=u_f0Wihq2Xw&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "5:18",
      "table": "Bảng B",
      "team1": "Anh",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Anh",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/DTqIL8Ba3KIuxGkpXw5ayA_96x96.png",
      "team2": "Iran",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Iran",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/1oq8Fy7ETpBpZNaCA22ArQ_96x96.png",
      "score": [6, 2],
      "scorerName1": ["Jude Victor William Bellingham 35'", "Bukayo Saka 43', 62'", "Raheem Shaquille Sterling 45+1'",
      "Marcus Rashford 71'", "Jack Peter Grealish 90'"],
      "scorerName2": ["Mehdi Taremi 65', 90+13'"],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/nIL5Cj5xYsLU-aeb_768x432.jpg",
      "id": "2"
    },
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Al Thumama Stadium",
      "linkStadium": "https://www.google.com/search?q=Al Thumama Stadium",
      "date": "21/11",
      "video": "https://www.youtube.com/watch?v=nvKnVVksSis&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "5:10",
      "table": "Bảng A",
      "team1": "Sénégal",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_S%C3%A9n%C3%A9gal",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/zw3ac5sIbH4DS6zP5auOkQ_96x96.png",
      "team2": "Hà Lan",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_H%C3%A0_Lan",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/8GEqzfLegwFFpe6X2BODTg_96x96.png",
      "score": [0, 2],
      "scorerName1": [''],
      "scorerName2": ["Cody Mathès Gakpo 84'", "Davy Klaassen 90+3'"],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/Qz6_ZhRdm2wNnMQj_768x432.jpg",
      "id": "3"
    }
  ],
  "22/11": [
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Ahmed bin Ali Stadium",
      "linkStadium": "https://www.google.com/search?q=Ahmed bin Ali Stadium",
      "date": "22/11",
      "video": "https://www.youtube.com/watch?v=1qjgILBOIDM&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "5:10",
      "table": "Bảng B",
      "team1": "Hoa Kỳ",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Hoa_K%E1%BB%B3",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/wj9uZvn_vZrelLFGH8fnPA_96x96.png",
      "team2": "Wales",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Wales",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/1JjnDm6Es30LryHzbudyEw_96x96.png",
      "score": [1, 1],
      "scorerName1": ["Timothy Tarpeh Weah 36'"],
      "scorerName2": ["Gareth Frank Bale 81'"],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/Ii5whnB1PhcIDJVy_768x432.jpg",
      "id": "4"
    },
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Lusail Stadium",
      "linkStadium": "https://www.google.com/search?q=Lusail Stadium",
      "date": "22/11",
      "video": "https://www.youtube.com/watch?v=23u4iy7vSvI&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "5:59",
      "table": "Bảng C",
      "team1": "Argentina",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Argentina",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/1xBWyjjkA6vEWopPK3lIPA_96x96.png",
      "team2": "Ả Rập Xê Út",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_%E1%BA%A2_R%E1%BA%ADp_X%C3%AA_%C3%9At",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/QoAJxO46fHid3_T-7nRZ0Q_96x96.png",
      "score": [1, 2],
      "scorerName1": ["Lionel Andrés Messi 10'"],
      "scorerName2": ["Saleh Al-Shehri 48'", "Salem Al-Dawsari 53'"],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/n_DPh_lbCN5pQio0_768x432.jpg",
      "id": "5"
    },
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Education City Stadium",
      "linkStadium": "https://www.google.com/search?q=Education City Stadium",
      "date": "22/11",
      "video": "https://www.youtube.com/watch?v=BJWhEWjA17g&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "4:11",
      "table": "Bảng D",
      "team1": "Đan Mạch",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_%C4%90an_M%E1%BA%A1ch",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/LaOvu-pyRqRso6uzff55XA_96x96.png",
      "team2": "Tunisia",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Tunisia",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/Xs33c9XVUJBX0IkeFn_bIw_96x96.png",
      "score": [0, 0],
      "scorerName1": [''],
      "scorerName2": [''],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/Rj78lmIOEv60ZYmT_768x432.jpg",
      "id": "6"
    },
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Estadio 0 9 7 4",
      "linkStadium": "https://www.google.com/search?q=Estadio 0 9 7 4",
      "date": "22/11",
      "video": "https://www.youtube.com/watch?v=4V-MNWx9M4I&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "5:41",
      "table": "Bảng C",
      "team1": "Mexico",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_M%C3%A9xico",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/yJF9xqmUGenD8108FJbg9A_96x96.png",
      "team2": "Ba Lan",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Ba_Lan",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/yTS_Piy3M1wUBnqU0n5aAw_96x96.png",
      "score": [0, 0],
      "scorerName1": [],
      "scorerName2": [],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/Fx3IIAX3f3GnTKaX_768x432.jpg",
      "id": "7"
    }
  ],
  "23/11": [
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Al Janoub Stadium",
      "linkStadium": "https://www.google.com/search?q=Al Janoub Stadium",
      "date": "23/11",
      "video": "https://www.youtube.com/watch?v=h9IKpBRrzrI&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "6:02",
      "table": "Bảng D",
      "team1": "Pháp",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Ph%C3%A1p",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/z3JEQB3coEAGLCJBEUzQ2A_96x96.png",
      "team2": "Úc",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_%C3%9Ac",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/jSgw5z0EPOLzdUi-Aomq7Q_96x96.png",
      "score": [4, 1],
      "scorerName1": ["Adrien Rabiot-Provost 27'", "Olivier Giroud 32', 71'", "Kylian Mbappé 68'"],
      "scorerName2": ["Craig Alexander Goodwin 9'"],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/YQsfEelTlKiZBT94_768x432.jpg",
      "id": "8"
    },
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Al Bayt Stadium",
      "linkStadium": "https://www.google.com/search?q=Al Bayt Stadium",
      "date": "23/11",
      "video": "https://www.youtube.com/watch?v=pvpxqO7C6jE&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "5:24",
      "table": "Bảng F",
      "team1": "Maroc",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Maroc",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/I3gt2Ew39ux3GGdZ-4JE3g_96x96.png",
      "team2": "Croatia",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Croatia",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/9toerdOg8xW4CRhDaZxsyw_96x96.png",
      "score": [0, 0],
      "scorerName1": [''],
      "scorerName2": [''],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/ZWXNqPcRQbz8OgCz_768x432.jpg",
      "id": "9"
    },
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Sân vận động Quốc tế Khalifa",
      "linkStadium": "https://www.google.com/search?q=Sân vận động Quốc tế Khalifa",
      "date": "23/11",
      "video": "https://www.youtube.com/watch?v=A6SRB6seTSk&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "7:53",
      "table": "Bảng E",
      "team1": "Đức",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_%C4%90%E1%BB%A9c",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/h1FhPLmDg9AHXzhygqvVPg_96x96.png",
      "team2": "Nhật",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Nh%E1%BA%ADt_B%E1%BA%A3n",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/by4OltvtZz7taxuQtkiP3A_96x96.png",
      "score": [1, 2],
      "scorerName1": ["İlkay Gündoğan 33'"],
      "scorerName2": ["Dōan Ritsu 75'", "Asano Takuma 83'"],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/_MlzaCZNx8xLYuRZ_768x432.jpg",
      "id": "10"
    },
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Al Thumama Stadium",
      "linkStadium": "https://www.google.com/search?q=Al Thumama Stadium",
      "date": "23/11",
      "video": "https://www.youtube.com/watch?v=qWilSWZXVAw&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "7:52",
      "table": "Bảng E",
      "team1": "Tây Ban Nha",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_T%C3%A2y_Ban_Nha",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/5hLkf7KFHhmpaiOJQv8LmA_96x96.png",
      "team2": "Costa Rica",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Costa_Rica",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/ixZiM5pj2IvvYc15k-zfeQ_96x96.png",
      "score": [7, 0],
      "scorerName1": ["Daniel Olmo Carvajal 11'", "Marco Asensio Willemsen 21'", "Ferran Torres Garcia 31', 54'",
      "Martín Páez Gavira 74'", "Carlos Soler Barragán 90'", "Álvaro Martín 90+2'"],
      "scorerName2": [''],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/fXJlGOoiWzBqgTd8_768x432.jpg",
      "id": "11"
    }
  ],
  "24/11": [
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Ahmed bin Ali Stadium",
      "linkStadium": "https://www.google.com/search?q=Ahmed bin Ali Stadium",
      "date": "24/11",
      "video": "https://www.youtube.com/watch?v=vFr-MS9-Gug&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "7:14",
      "table": "Bảng F",
      "team1": "Bỉ",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_B%E1%BB%89",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/6SF7yEoB60bU5knw-M7R5Q_96x96.png",
      "team2": "Canada",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Canada",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/H23oIEP6qK-zNc3O8abnIA_96x96.png",
      "score": [1, 0],
      "scorerName1": ["Michy Batshuayi-Atunga 44'"],
      "scorerName2": [''],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/zVcGDo6o2vny_hxt_768x432.jpg",
      "id": "12"
    },
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Al Janoub Stadium",
      "linkStadium": "https://www.google.com/search?q=Al Janoub Stadium",
      "date": "24/11",
      "video": "https://www.youtube.com/watch?v=eO5lYcpRJvU&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "7:57",
      "table": "Bảng G",
      "team1": "Thụy Sĩ",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Th%E1%BB%A5y_S%C4%A9",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/1hy9ek4dOIffYULM6k1fqg_96x96.png",
      "team2": "Cameroon",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Cameroon",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/fmHyTSbJ-cYbY6WJzvqaZQ_96x96.png",
      "score": [1, 0],
      "scorerName1": ["Breel Donald Embolo 48'"],
      "scorerName2": [''],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/iUiUDMgiX07101zW_768x432.jpg",
      "id": "13"
    },
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Education City Stadium",
      "linkStadium": "https://www.google.com/search?q=Education City Stadium",
      "date": "24/11",
      "video": "https://www.youtube.com/watch?v=HIujug2OhEE&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "7:28",
      "table": "Bảng H",
      "team1": "Uruguay",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Uruguay",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/KnSUdQWiGRoy89q4x85IgA_96x96.png",
      "team2": "Hàn Quốc",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_H%C3%A0n_Qu%E1%BB%91c",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/Uu5pwNmMHGd5bCooKrS3Lw_96x96.png",
      "score": [0, 0],
      "scorerName1": [''],
      "scorerName2": [''],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/2A5cYzttXQqVyapp_768x432.jpg",
      "id": "14"
    },
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Estadio 0 9 7 4",
      "linkStadium": "https://www.google.com/search?q=Estadio 0 9 7 4",
      "date": "24/11",
      "video": "https://www.youtube.com/watch?v=bSKAzou_gXM&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "8:02",
      "table": "Bảng H",
      "team1": "Bồ Đào Nha",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_B%E1%BB%93_%C4%90%C3%A0o_Nha",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/HJ3_2c4w791nZJj7n-Lj3Q_96x96.png",
      "team2": "Ghana",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Ghana",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/VJQ1emg0TOubjGnap4vWuw_96x96.png",
      "score": [3, 2],
      "scorerName1": ["Cristiano Ronaldo 65'", "João Félix Sequeira 78'", "Rafael Alexandre 80'"],
      "scorerName2": ["André Ayew Rami 73'", "Osman Bukari 89'"],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/CJkn2z7OoNVpP5_t_768x432.jpg",
      "id": "15"
    }
  ],
  "25/11": [
    {
      "groupStage": "Vòng đấu bảng",
      "stadium": "Lusail Stadium",
      "linkStadium": "https://www.google.com/search?q=Lusail Stadium",
      "date": "25/11",
      "video": "https://www.youtube.com/watch?v=Xx6YaUIMuRQ&ab_channel=VTVTh%E1%BB%83Thao",
      "timehighlight": "7:57",
      "table": "Bảng G",
      "team1": "Brasil",
      "linkTeam1": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Brasil",
      "image1": "https://ssl.gstatic.com/onebox/media/sports/logos/zKLzoJVYz0bb6oAnPUdwWQ_96x96.png",
      "team2": "Serbia",
      "linkTeam2": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%99i_tuy%E1%BB%83n_b%C3%B3ng_%C4%91%C3%A1_qu%E1%BB%91c_gia_Serbia",
      "image2": "https://ssl.gstatic.com/onebox/media/sports/logos/xyh1vmZ-xJH2iJCKjqS1Ow_96x96.png",
      "score": [2, 0],
      "scorerName1": ["Richarlison de Andrade 62', 73'"],
      "scorerName2": [''],
      "imagehighlight": "https://ssl.gstatic.com/onebox/media/sports/videos/vita/c7_7DBKAV5pVyww1_768x432.jpg",
      "id": "16"
    }
  ]
}
